language: c
sudo: false
dist: bionic

matrix:
  include:
    - os: linux
      env: CC=gcc-5

    - os: linux
      env: CC=gcc-6

    - os: linux
      env: CC=gcc-7

    - os: linux
      env: CC=gcc-8

    - os: linux
      env: CC=clang-5.0

    - os: linux
      env: CC=clang-6.0

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-5 gcc-6 gcc-7 gcc-8 clang-5.0 clang-6.0 clang-8 libgpiod-dev
script: make
